[2021-04-18 16:36:49,420] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_kc_crime_data-v0.1.is_api_available 2021-04-17T00:00:00+00:00 [queued]>
[2021-04-18 16:36:49,458] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_kc_crime_data-v0.1.is_api_available 2021-04-17T00:00:00+00:00 [queued]>
[2021-04-18 16:36:49,459] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-18 16:36:49,460] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-04-18 16:36:49,460] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-18 16:36:49,471] {taskinstance.py:1063} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-04-17T00:00:00+00:00
[2021-04-18 16:36:49,477] {standard_task_runner.py:52} INFO - Started process 1213 to run task
[2021-04-18 16:36:49,481] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_kc_crime_data-v0.1', 'is_api_available', '2021-04-17T00:00:00+00:00', '--job-id', '4', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/fetch_kc_crime_data-v0.1.py', '--cfg-path', '/tmp/tmpp33oekn3', '--error-file', '/tmp/tmpq16fn95u']
[2021-04-18 16:36:49,486] {standard_task_runner.py:77} INFO - Job 4: Subtask is_api_available
[2021-04-18 16:36:49,573] {logging_mixin.py:104} INFO - Running <TaskInstance: fetch_kc_crime_data-v0.1.is_api_available 2021-04-17T00:00:00+00:00 [running]> on host 441e26371bd5
[2021-04-18 16:36:49,684] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=fetch_kc_crime_data-v0.1
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-04-17T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-17T00:00:00+00:00
[2021-04-18 16:36:49,687] {http.py:102} INFO - Poking: resource/w795-ffu6.json
[2021-04-18 16:36:49,728] {taskinstance.py:1455} ERROR - The conn_id `http_data_kcmo_org` isn't defined
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/sensors/base.py", line 228, in execute
    while not self.poke(context):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/http/sensors/http.py", line 118, in poke
    raise exc
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/http/sensors/http.py", line 108, in poke
    extra_options=self.extra_options,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/http/hooks/http.py", line 122, in run
    session = self.get_conn(headers)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/http/hooks/http.py", line 72, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 63, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 354, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `http_data_kcmo_org` isn't defined
[2021-04-18 16:36:49,733] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=fetch_kc_crime_data-v0.1, task_id=is_api_available, execution_date=20210417T000000, start_date=20210418T163649, end_date=20210418T163649
[2021-04-18 16:36:49,816] {local_task_job.py:146} INFO - Task exited with return code 1
[2021-04-18 16:47:32,841] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_kc_crime_data-v0.1.is_api_available 2021-04-17T00:00:00+00:00 [queued]>
[2021-04-18 16:47:32,904] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_kc_crime_data-v0.1.is_api_available 2021-04-17T00:00:00+00:00 [queued]>
[2021-04-18 16:47:32,907] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-18 16:47:32,908] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-04-18 16:47:32,909] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-18 16:47:32,927] {taskinstance.py:1063} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-04-17T00:00:00+00:00
[2021-04-18 16:47:32,942] {standard_task_runner.py:52} INFO - Started process 217 to run task
[2021-04-18 16:47:32,949] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_kc_crime_data-v0.1', 'is_api_available', '2021-04-17T00:00:00+00:00', '--job-id', '2', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/fetch_kc_crime_data-v0.1.py', '--cfg-path', '/tmp/tmpys6r8mzz', '--error-file', '/tmp/tmpdwux9z63']
[2021-04-18 16:47:32,956] {standard_task_runner.py:77} INFO - Job 2: Subtask is_api_available
[2021-04-18 16:47:33,146] {logging_mixin.py:104} INFO - Running <TaskInstance: fetch_kc_crime_data-v0.1.is_api_available 2021-04-17T00:00:00+00:00 [running]> on host 9651c4896f9f
[2021-04-18 16:47:33,476] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=fetch_kc_crime_data-v0.1
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-04-17T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-17T00:00:00+00:00
[2021-04-18 16:47:33,484] {http.py:102} INFO - Poking: resource/w795-ffu6.json
[2021-04-18 16:47:33,686] {taskinstance.py:1455} ERROR - The conn_id `http_data_kcmo_org` isn't defined
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/sensors/base.py", line 228, in execute
    while not self.poke(context):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/http/sensors/http.py", line 118, in poke
    raise exc
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/http/sensors/http.py", line 108, in poke
    extra_options=self.extra_options,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/http/hooks/http.py", line 122, in run
    session = self.get_conn(headers)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/http/hooks/http.py", line 72, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/base.py", line 63, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/connection.py", line 354, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `http_data_kcmo_org` isn't defined
[2021-04-18 16:47:33,691] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=fetch_kc_crime_data-v0.1, task_id=is_api_available, execution_date=20210417T000000, start_date=20210418T164732, end_date=20210418T164733
[2021-04-18 16:47:33,848] {local_task_job.py:146} INFO - Task exited with return code 1
