[2021-04-18 17:04:12,210] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_kc_crime_data-v0.1.download_latest_crime_data 2021-04-18T17:04:01.756171+00:00 [queued]>
[2021-04-18 17:04:12,278] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_kc_crime_data-v0.1.download_latest_crime_data 2021-04-18T17:04:01.756171+00:00 [queued]>
[2021-04-18 17:04:12,279] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-18 17:04:12,280] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-04-18 17:04:12,281] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-18 17:04:12,295] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): download_latest_crime_data> on 2021-04-18T17:04:01.756171+00:00
[2021-04-18 17:04:12,303] {standard_task_runner.py:52} INFO - Started process 1204 to run task
[2021-04-18 17:04:12,314] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_kc_crime_data-v0.1', 'download_latest_crime_data', '2021-04-18T17:04:01.756171+00:00', '--job-id', '17', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/fetch_kc_crime_data-v0.1.py', '--cfg-path', '/tmp/tmp3jj5zjm8', '--error-file', '/tmp/tmpaxrr8uek']
[2021-04-18 17:04:12,325] {standard_task_runner.py:77} INFO - Job 17: Subtask download_latest_crime_data
[2021-04-18 17:04:12,461] {logging_mixin.py:104} INFO - Running <TaskInstance: fetch_kc_crime_data-v0.1.download_latest_crime_data 2021-04-18T17:04:01.756171+00:00 [running]> on host 9651c4896f9f
[2021-04-18 17:04:12,567] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=fetch_kc_crime_data-v0.1
AIRFLOW_CTX_TASK_ID=download_latest_crime_data
AIRFLOW_CTX_EXECUTION_DATE=2021-04-18T17:04:01.756171+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-04-18T17:04:01.756171+00:00
[2021-04-18 17:04:12,602] {logging_mixin.py:104} INFO - Min Window: 2021-01-01T00:00:00.000
[2021-04-18 17:04:12,603] {logging_mixin.py:104} INFO - Max Window: 2021-04-18T17:04:09.313
[2021-04-18 17:04:12,604] {logging_mixin.py:104} INFO - {'$where': "report_date BETWEEN '2021-01-01T00:00:00.000' and '2021-04-18T17:04:09.313'"}
[2021-04-18 17:04:13,152] {logging_mixin.py:104} INFO - Output file: /opt/airflow/dags/data/2021-04-18.json
[2021-04-18 17:04:13,154] {taskinstance.py:1455} ERROR - [Errno 2] No such file or directory: '/opt/airflow/dags/data/2021-04-18.json'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fetch_kc_crime_data-v0.1.py", line 75, in download_latest_crime_data
    with open(tot_name, 'w') as outputfile:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/2021-04-18.json'
[2021-04-18 17:04:13,158] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=fetch_kc_crime_data-v0.1, task_id=download_latest_crime_data, execution_date=20210418T170401, start_date=20210418T170412, end_date=20210418T170413
[2021-04-18 17:04:13,214] {local_task_job.py:146} INFO - Task exited with return code 1
