[2021-04-18 17:00:18,281] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_kc_crime_data-v0.1.load_data_raw 2021-04-18T17:00:02.895656+00:00 [queued]>
[2021-04-18 17:00:18,317] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_kc_crime_data-v0.1.load_data_raw 2021-04-18T17:00:02.895656+00:00 [queued]>
[2021-04-18 17:00:18,318] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-18 17:00:18,319] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-04-18 17:00:18,320] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-18 17:00:18,332] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): load_data_raw> on 2021-04-18T17:00:02.895656+00:00
[2021-04-18 17:00:18,341] {standard_task_runner.py:52} INFO - Started process 987 to run task
[2021-04-18 17:00:18,346] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_kc_crime_data-v0.1', 'load_data_raw', '2021-04-18T17:00:02.895656+00:00', '--job-id', '14', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/fetch_kc_crime_data-v0.1.py', '--cfg-path', '/tmp/tmp3orfe39e', '--error-file', '/tmp/tmpaje690mt']
[2021-04-18 17:00:18,351] {standard_task_runner.py:77} INFO - Job 14: Subtask load_data_raw
[2021-04-18 17:00:18,446] {logging_mixin.py:104} INFO - Running <TaskInstance: fetch_kc_crime_data-v0.1.load_data_raw 2021-04-18T17:00:02.895656+00:00 [running]> on host 9651c4896f9f
[2021-04-18 17:00:18,537] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=fetch_kc_crime_data-v0.1
AIRFLOW_CTX_TASK_ID=load_data_raw
AIRFLOW_CTX_EXECUTION_DATE=2021-04-18T17:00:02.895656+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-04-18T17:00:02.895656+00:00
[2021-04-18 17:00:18,569] {logging_mixin.py:104} INFO - Output file: /opt/airflow/dags/data/2021-04-18.json
[2021-04-18 17:00:18,571] {taskinstance.py:1455} ERROR - [Errno 2] No such file or directory: '/opt/airflow/dags/data/2021-04-18.json'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fetch_kc_crime_data-v0.1.py", line 87, in load_data_raw
    with open(tot_name, 'r') as inputfile:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data/2021-04-18.json'
[2021-04-18 17:00:18,575] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=fetch_kc_crime_data-v0.1, task_id=load_data_raw, execution_date=20210418T170002, start_date=20210418T170018, end_date=20210418T170018
[2021-04-18 17:00:18,642] {local_task_job.py:146} INFO - Task exited with return code 1
