[2021-04-18 16:49:14,233] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_kc_crime_data-v0.1.fetch_crime_window 2021-04-18T16:47:32.702474+00:00 [queued]>
[2021-04-18 16:49:14,265] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_kc_crime_data-v0.1.fetch_crime_window 2021-04-18T16:47:32.702474+00:00 [queued]>
[2021-04-18 16:49:14,265] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-18 16:49:14,266] {taskinstance.py:1043} INFO - Starting attempt 2 of 2
[2021-04-18 16:49:14,267] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-18 16:49:14,278] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): fetch_crime_window> on 2021-04-18T16:47:32.702474+00:00
[2021-04-18 16:49:14,285] {standard_task_runner.py:52} INFO - Started process 330 to run task
[2021-04-18 16:49:14,290] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_kc_crime_data-v0.1', 'fetch_crime_window', '2021-04-18T16:47:32.702474+00:00', '--job-id', '6', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/fetch_kc_crime_data-v0.1.py', '--cfg-path', '/tmp/tmphzv75rj4', '--error-file', '/tmp/tmp8bev_ck1']
[2021-04-18 16:49:14,295] {standard_task_runner.py:77} INFO - Job 6: Subtask fetch_crime_window
[2021-04-18 16:49:14,381] {logging_mixin.py:104} INFO - Running <TaskInstance: fetch_kc_crime_data-v0.1.fetch_crime_window 2021-04-18T16:47:32.702474+00:00 [running]> on host 9651c4896f9f
[2021-04-18 16:49:14,470] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=fetch_kc_crime_data-v0.1
AIRFLOW_CTX_TASK_ID=fetch_crime_window
AIRFLOW_CTX_EXECUTION_DATE=2021-04-18T16:47:32.702474+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-04-18T16:47:32.702474+00:00
[2021-04-18 16:49:14,538] {base.py:74} INFO - Using connection to: id: pg_kcmo_opendata. Host: postgres, Port: 5432, Schema: kcmo, Login: data_user, Password: XXXXXXXX, extra: None
[2021-04-18 16:49:14,952] {taskinstance.py:1455} ERROR - relation "public.crime_2021_raw" does not exist
LINE 1: ...r(window_end, 'YYYY-MM-DD"T"HH24:MI:ss.ms')) from public.cri...
                                                             ^
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fetch_kc_crime_data-v0.1.py", line 40, in fetch_crime_window
    cursor.execute(select)
psycopg2.errors.UndefinedTable: relation "public.crime_2021_raw" does not exist
LINE 1: ...r(window_end, 'YYYY-MM-DD"T"HH24:MI:ss.ms')) from public.cri...
                                                             ^

[2021-04-18 16:49:14,967] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=fetch_kc_crime_data-v0.1, task_id=fetch_crime_window, execution_date=20210418T164732, start_date=20210418T164914, end_date=20210418T164914
[2021-04-18 16:49:15,136] {local_task_job.py:146} INFO - Task exited with return code 1
